apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  namespace: default
  labels:
    app: client-pod
spec:
  containers:
  - name: simple-fullstack-client
    image: jeralsandeeptha/simple-fullstack-client
    ports:
    - containerPort: 3000
      name:  http
    env:
    - name: REACT_APP_API_URL
      value: "http://localhost:30005/api" #this should be backend endpoint not localhost