apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: client-service
    env: production
spec:
  type: NodePort
  selector:
    app: client-pod
    env: production
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
