apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
  namespace: default
  labels:
    app: mongodb-pod
spec:
  containers:
  - name: mongodb
    image: mongo:latest
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: "jeral"
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: "1234" 
    ports:
    - containerPort: 27017
      name: http