apiVersion: v1
kind: Service
metadata:
  name: server-service
  labels:
    app: server-service
    env: production
spec:
  type: NodePort
  selector:
    app: server-pod
    env: production
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30500