apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: default
  labels:
    app: server-service
spec:
  selector:
    app: service-pod
  type: NodePort
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
      nodePort: 30005