apiVersion: v1
kind: Pod
metadata:
  name: service-pod
  namespace: default
  labels:
    app: service-pod
spec:
  containers:
  - name: simple-fullstack-server
    image: jeralsandeeptha/simple-fullstack-server
    env:
    - name: PORT
      value: "5000"
    - name: MONGO_URL
      value: "mongodb://jeral:1234@mongodb-service:27017"
    ports:
    - containerPort: 7000
      name: http