apiVersion: v1
kind: Secret
metadata:
  name: server-secret
data:
  MONGO_URL: bW9uZ29kYitzcnY6Ly9qZXJhbDoxMjM0QG1lcm4ta3ViLjE3Z2l6bWgubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPW1lcm4ta3Vi